safe: false
permalink: /:title.html
exclude:
  - README.md

name: Keptab Blog
desc: everything about Keptab

custom:
    links:
        - name: Keptab Apps
          link: https://keptab.com/apps
        
        - name: Keptab FAQ
          link: https://keptab.com/faq

        - name: Keptab Feedback
          link: https://keptab.com/feedback

meta:
    author:
        name: Keptab Team
        email: hi@keptab.com
        about: We create the Project Keptab, and share the story behind Keptab
    
    disqus:
        shortname: keptab
        embedjs: https://keptab.disqus.com/embed.js

    github:
        name: keptab
        fork: https://github.com/keptab/keptab-blog

    google:
        analytics: UA-123456-1
        analyticsjs: https://www.google-analytics.com/analytics.js
    
    twitter:
        name: keptab
        follow: https://twitter.com/keptab